[package]
name = "fanta-gpui-gpui-platform"
version = "0.2.0"
edition = "2024"
publish = true
license = "Apache-2.0"
repository = "https://github.com/squidred-dev/fanta-ui"
description = "Fanta GPUI fork of gpui_platform"

[lib]
path = "src/gpui_platform.rs"
name = "gpui_platform"

[features]
default = []
font-kit = [ "gpui_macos/font-kit",]
test-support = [ "gpui/test-support", "gpui_macos/test-support",]
screen-capture = [ "gpui/screen-capture", "gpui_macos/screen-capture", "gpui_windows/screen-capture", "gpui_linux/screen-capture",]
runtime_shaders = [ "gpui_macos/runtime_shaders",]
wayland = [ "gpui_linux/wayland",]
x11 = [ "gpui_linux/x11",]

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
declare_interior_mutable_const = "deny"
redundant_clone = "deny"
disallowed_methods = "deny"
type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"

[dependencies.gpui]
path = "../gpui"
default-features = false
package = "fanta-gpui-core"
version = "=0.2.0"

[lints.clippy.style]
level = "allow"
priority = -1

[lints.rust.unexpected_cfgs]
level = "allow"

[target."cfg(target_family = \"wasm\")".dependencies]
console_error_panic_hook = "0.1.7"

[target."cfg(target_family = \"wasm\")".dependencies.gpui_web]
path = "../gpui_web"
package = "fanta-gpui-gpui-web"
version = "=0.2.0"

[target."cfg(target_os = \"macos\")".dependencies.gpui_macos]
path = "../gpui_macos"
default-features = false
package = "fanta-gpui-gpui-macos"
version = "=0.2.0"

[target."cfg(target_os = \"windows\")".dependencies.gpui_windows]
path = "../gpui_windows"
default-features = false
package = "fanta-gpui-gpui-windows"
version = "=0.2.0"

[target."cfg(target_os = \"windows\")".dependencies.gpui]
path = "../gpui"
default-features = false
features = [ "windows-manifest",]
package = "fanta-gpui-core"
version = "=0.2.0"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.gpui_linux]
path = "../gpui_linux"
default-features = false
package = "fanta-gpui-gpui-linux"
version = "=0.2.0"
