[workspace]
resolver = "2"
members = [
    "crates/async_process",
    "crates/collections",
    "crates/fanta-gpui",
    "crates/fanta-gpui-storybook",
    "crates/gpui",
    "crates/gpui-examples",
    "crates/gpui-macro-tests",
    "crates/gpui_component",
    "crates/gpui_component_assets",
    "crates/gpui_linux",
    "crates/gpui_macos",
    "crates/gpui_macros",
    "crates/gpui_platform",
    "crates/gpui_shared_string",
    "crates/gpui_tokio",
    "crates/gpui_util",
    "crates/gpui_web",
    "crates/gpui_wgpu",
    "crates/gpui_windows",
    "crates/http_client",
    "crates/http_client_tls",
    "crates/media",
    "crates/proptest",
    "crates/proptest-macro",
    "crates/refineable",
    "crates/refineable/derive_refineable",
    "crates/reqwest_client",
    "crates/scheduler",
    "crates/smol",
    "crates/sum_tree",
    "crates/util",
    "crates/util_macros",
    "crates/zlog",
    "crates/ztracing",
    "crates/ztracing_macro",
    "tooling/perf",
]
default-members = ["crates/fanta-gpui"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.95"
publish = false
license = "GPL-3.0"
repository = "https://github.com/squidred-dev/fanta-ui"

[workspace.dependencies]
fanta-gpui = { path = "crates/fanta-gpui", version = "=0.2.0" }
gpui = { package = "fanta-gpui-core", path = "crates/gpui", version = "=0.2.0" }
gpui-component = { package = "fanta-gpui-components", path = "crates/gpui_component", version = "=0.2.0" }
gpui-component-assets = { package = "fanta-gpui-component-assets", path = "crates/gpui_component_assets", version = "=0.2.0" }
gpui_platform = { package = "fanta-gpui-gpui-platform", path = "crates/gpui_platform", version = "=0.2.0", default-features = false, features = ["font-kit", "wayland", "x11"] }
serde_json = "1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"

[profile.dev]
codegen-units = 16
debug = "limited"
split-debuginfo = "unpacked"

[profile.dev.package.fanta-gpui-core]
opt-level = 3
