[package]
name = "fanta-gpui-gpui-linux"
version = "0.4.1"
edition = "2024"
publish = true
license = "Apache-2.0"
repository = "https://github.com/squidred-dev/fanta-ui"
description = "Fanta GPUI fork of gpui_linux"

[lib]
path = "src/gpui_linux.rs"
name = "gpui_linux"

[features]
default = [ "wayland", "x11",]
test-support = [ "gpui/test-support",]
wayland = [ "bitflags", "gpui_wgpu", "ashpd/wayland", "calloop-wayland-source", "wayland-backend", "wayland-client", "wayland-cursor", "wayland-protocols", "wayland-protocols-plasma", "wayland-protocols-wlr", "filedescriptor", "xkbcommon", "open", "gpui/wayland",]
x11 = [ "gpui_wgpu", "ashpd", "as-raw-xcb-connection", "x11rb", "xkbcommon", "xim", "x11-clipboard", "filedescriptor", "open", "scap?/x11",]
screen-capture = [ "gpui/screen-capture", "scap",]

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
declare_interior_mutable_const = "deny"
redundant_clone = "deny"
disallowed_methods = "deny"
type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"

[lints.clippy.style]
level = "allow"
priority = -1

[lints.rust.unexpected_cfgs]
level = "allow"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies]
bytemuck = "1"
pathfinder_geometry = "0.5"
calloop = "0.14.3"
raw-window-handle = "0.6"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.accesskit]
version = "0.24.0"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.accesskit_unix]
version = "0.21.0"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.anyhow]
version = "1.0.86"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.collections]
path = "../collections"
version = "=0.4.1"
package = "fanta-gpui-collections"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.image]
version = "0.25.1"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.futures]
version = "0.3.32"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.gpui]
path = "../gpui"
default-features = false
package = "fanta-gpui-core"
version = "=0.4.1"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.gpui_util]
path = "../gpui_util"
package = "fanta-gpui-gpui-util"
version = "=0.4.1"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.gpui_wgpu]
path = "../gpui_wgpu"
optional = true
features = [ "font-kit",]
package = "fanta-gpui-gpui-wgpu"
version = "=0.4.1"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.http_client]
path = "../http_client"
package = "fanta-gpui-http-client"
version = "=0.4.1"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.itertools]
version = "0.14.0"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.libc]
version = "0.2"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.log]
version = "0.4.16"
features = [ "kv_unstable_serde", "serde",]

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.parking_lot]
version = "0.12.1"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.pollster]
version = "0.4.0"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.profiling]
version = "1"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.smallvec]
version = "1.6"
features = [ "const_new", "union",]

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.smol]
version = "=0.4.1"
package = "fanta-gpui-smol"
path = "../smol"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.strum]
version = "0.27.2"
features = [ "derive",]

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.url]
version = "2.2"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.uuid]
version = "1.1.2"
features = [ "serde", "v4", "v5", "v7",]

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.oo7]
version = "0.6"
default-features = false
features = [ "async-std", "native_crypto",]

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.ashpd]
version = "0.13"
default-features = false
features = [ "async-io", "file_chooser", "notification", "open_uri", "settings", "trash",]
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.swash]
version = "0.2.6"

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.bitflags]
version = "2.6.0"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.filedescriptor]
version = "0.8.2"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.open]
version = "5.2.0"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.xkbcommon]
version = "0.8.0"
features = [ "wayland", "x11",]
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.scap]
default-features = false
package = "zed-scap"
version = "0.0.8-zed"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.calloop-wayland-source]
version = "0.4.1"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.wayland-backend]
version = "0.3.3"
features = [ "client_system", "dlopen",]
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.wayland-client]
version = "0.31.11"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.wayland-cursor]
version = "0.31.11"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.wayland-protocols]
version = "0.32.9"
features = [ "client", "staging", "unstable",]
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.wayland-protocols-plasma]
version = "0.3.9"
features = [ "client",]
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.wayland-protocols-wlr]
version = "0.3.9"
features = [ "client",]
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.as-raw-xcb-connection]
version = "1"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.x11rb]
version = "0.13.1"
features = [ "allow-unsafe-code", "xkb", "randr", "xinput", "cursor", "resource_manager", "sync", "dri3",]
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.xim]
features = [ "x11rb-xcb", "x11rb-client",]
package = "zed-xim"
version = "0.4.0-zed"
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.x11-clipboard]
version = "0.9.3"
optional = true
