[package]
name = "fanta-gpui-gpui-tokio"
version = "0.1.0"
edition = "2024"
publish = true
license = "Apache-2.0"
repository = "https://github.com/squidred-dev/fanta-ui"
description = "Fanta GPUI fork of gpui_tokio"

[lib]
path = "src/gpui_tokio.rs"
doctest = false
name = "gpui_tokio"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
declare_interior_mutable_const = "deny"
redundant_clone = "deny"
disallowed_methods = "deny"
type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"

[dependencies.anyhow]
version = "1.0.86"

[dependencies.gpui]
path = "../gpui"
default-features = false
package = "fanta-gpui-core"
version = "=0.1.0"

[dependencies.gpui_util]
path = "../gpui_util"
package = "fanta-gpui-gpui-util"
version = "=0.1.0"

[dependencies.tokio]
version = "1"
features = [ "rt", "rt-multi-thread",]

[lints.clippy.style]
level = "allow"
priority = -1

[lints.rust.unexpected_cfgs]
level = "allow"
